// flow-typed signature: 8af9d8165acb3d5aa6e388a057177ca7
// flow-typed version: <<STUB>>/react-player_v2.7.0/flow_v0.106.3

/**
 * This is an autogenerated libdef stub for:
 *
 *   'react-player'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'react-player' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'react-player/dailymotion' {
  declare module.exports: any;
}

declare module 'react-player/dist/ReactPlayer' {
  declare module.exports: any;
}

declare module 'react-player/dist/ReactPlayer.standalone' {
  declare module.exports: any;
}

declare module 'react-player/facebook' {
  declare module.exports: any;
}

declare module 'react-player/file' {
  declare module.exports: any;
}

declare module 'react-player/lazy' {
  declare module.exports: any;
}

declare module 'react-player/lazy/patterns' {
  declare module.exports: any;
}

declare module 'react-player/lazy/Player' {
  declare module.exports: any;
}

declare module 'react-player/lazy/players/DailyMotion' {
  declare module.exports: any;
}

declare module 'react-player/lazy/players/Facebook' {
  declare module.exports: any;
}

declare module 'react-player/lazy/players/FilePlayer' {
  declare module.exports: any;
}

declare module 'react-player/lazy/players' {
  declare module.exports: any;
}

declare module 'react-player/lazy/players/Mixcloud' {
  declare module.exports: any;
}

declare module 'react-player/lazy/players/SoundCloud' {
  declare module.exports: any;
}

declare module 'react-player/lazy/players/Streamable' {
  declare module.exports: any;
}

declare module 'react-player/lazy/players/Twitch' {
  declare module.exports: any;
}

declare module 'react-player/lazy/players/Vidyard' {
  declare module.exports: any;
}

declare module 'react-player/lazy/players/Vimeo' {
  declare module.exports: any;
}

declare module 'react-player/lazy/players/Wistia' {
  declare module.exports: any;
}

declare module 'react-player/lazy/players/YouTube' {
  declare module.exports: any;
}

declare module 'react-player/lazy/Preview' {
  declare module.exports: any;
}

declare module 'react-player/lazy/props' {
  declare module.exports: any;
}

declare module 'react-player/lazy/ReactPlayer' {
  declare module.exports: any;
}

declare module 'react-player/lazy/standalone' {
  declare module.exports: any;
}

declare module 'react-player/lazy/utils' {
  declare module.exports: any;
}

declare module 'react-player/lib' {
  declare module.exports: any;
}

declare module 'react-player/lib/patterns' {
  declare module.exports: any;
}

declare module 'react-player/lib/Player' {
  declare module.exports: any;
}

declare module 'react-player/lib/players/DailyMotion' {
  declare module.exports: any;
}

declare module 'react-player/lib/players/Facebook' {
  declare module.exports: any;
}

declare module 'react-player/lib/players/FilePlayer' {
  declare module.exports: any;
}

declare module 'react-player/lib/players' {
  declare module.exports: any;
}

declare module 'react-player/lib/players/Mixcloud' {
  declare module.exports: any;
}

declare module 'react-player/lib/players/SoundCloud' {
  declare module.exports: any;
}

declare module 'react-player/lib/players/Streamable' {
  declare module.exports: any;
}

declare module 'react-player/lib/players/Twitch' {
  declare module.exports: any;
}

declare module 'react-player/lib/players/Vidyard' {
  declare module.exports: any;
}

declare module 'react-player/lib/players/Vimeo' {
  declare module.exports: any;
}

declare module 'react-player/lib/players/Wistia' {
  declare module.exports: any;
}

declare module 'react-player/lib/players/YouTube' {
  declare module.exports: any;
}

declare module 'react-player/lib/Preview' {
  declare module.exports: any;
}

declare module 'react-player/lib/props' {
  declare module.exports: any;
}

declare module 'react-player/lib/ReactPlayer' {
  declare module.exports: any;
}

declare module 'react-player/lib/standalone' {
  declare module.exports: any;
}

declare module 'react-player/lib/utils' {
  declare module.exports: any;
}

declare module 'react-player/mixcloud' {
  declare module.exports: any;
}

declare module 'react-player/scripts/post-publish' {
  declare module.exports: any;
}

declare module 'react-player/scripts/pre-publish' {
  declare module.exports: any;
}

declare module 'react-player/soundcloud' {
  declare module.exports: any;
}

declare module 'react-player/streamable' {
  declare module.exports: any;
}

declare module 'react-player/twitch' {
  declare module.exports: any;
}

declare module 'react-player/vidyard' {
  declare module.exports: any;
}

declare module 'react-player/vimeo' {
  declare module.exports: any;
}

declare module 'react-player/wistia' {
  declare module.exports: any;
}

declare module 'react-player/youtube' {
  declare module.exports: any;
}

// Filename aliases
declare module 'react-player/dailymotion.js' {
  declare module.exports: $Exports<'react-player/dailymotion'>;
}
declare module 'react-player/dist/ReactPlayer.js' {
  declare module.exports: $Exports<'react-player/dist/ReactPlayer'>;
}
declare module 'react-player/dist/ReactPlayer.standalone.js' {
  declare module.exports: $Exports<'react-player/dist/ReactPlayer.standalone'>;
}
declare module 'react-player/facebook.js' {
  declare module.exports: $Exports<'react-player/facebook'>;
}
declare module 'react-player/file.js' {
  declare module.exports: $Exports<'react-player/file'>;
}
declare module 'react-player/lazy/index' {
  declare module.exports: $Exports<'react-player/lazy'>;
}
declare module 'react-player/lazy/index.js' {
  declare module.exports: $Exports<'react-player/lazy'>;
}
declare module 'react-player/lazy/patterns.js' {
  declare module.exports: $Exports<'react-player/lazy/patterns'>;
}
declare module 'react-player/lazy/Player.js' {
  declare module.exports: $Exports<'react-player/lazy/Player'>;
}
declare module 'react-player/lazy/players/DailyMotion.js' {
  declare module.exports: $Exports<'react-player/lazy/players/DailyMotion'>;
}
declare module 'react-player/lazy/players/Facebook.js' {
  declare module.exports: $Exports<'react-player/lazy/players/Facebook'>;
}
declare module 'react-player/lazy/players/FilePlayer.js' {
  declare module.exports: $Exports<'react-player/lazy/players/FilePlayer'>;
}
declare module 'react-player/lazy/players/index' {
  declare module.exports: $Exports<'react-player/lazy/players'>;
}
declare module 'react-player/lazy/players/index.js' {
  declare module.exports: $Exports<'react-player/lazy/players'>;
}
declare module 'react-player/lazy/players/Mixcloud.js' {
  declare module.exports: $Exports<'react-player/lazy/players/Mixcloud'>;
}
declare module 'react-player/lazy/players/SoundCloud.js' {
  declare module.exports: $Exports<'react-player/lazy/players/SoundCloud'>;
}
declare module 'react-player/lazy/players/Streamable.js' {
  declare module.exports: $Exports<'react-player/lazy/players/Streamable'>;
}
declare module 'react-player/lazy/players/Twitch.js' {
  declare module.exports: $Exports<'react-player/lazy/players/Twitch'>;
}
declare module 'react-player/lazy/players/Vidyard.js' {
  declare module.exports: $Exports<'react-player/lazy/players/Vidyard'>;
}
declare module 'react-player/lazy/players/Vimeo.js' {
  declare module.exports: $Exports<'react-player/lazy/players/Vimeo'>;
}
declare module 'react-player/lazy/players/Wistia.js' {
  declare module.exports: $Exports<'react-player/lazy/players/Wistia'>;
}
declare module 'react-player/lazy/players/YouTube.js' {
  declare module.exports: $Exports<'react-player/lazy/players/YouTube'>;
}
declare module 'react-player/lazy/Preview.js' {
  declare module.exports: $Exports<'react-player/lazy/Preview'>;
}
declare module 'react-player/lazy/props.js' {
  declare module.exports: $Exports<'react-player/lazy/props'>;
}
declare module 'react-player/lazy/ReactPlayer.js' {
  declare module.exports: $Exports<'react-player/lazy/ReactPlayer'>;
}
declare module 'react-player/lazy/standalone.js' {
  declare module.exports: $Exports<'react-player/lazy/standalone'>;
}
declare module 'react-player/lazy/utils.js' {
  declare module.exports: $Exports<'react-player/lazy/utils'>;
}
declare module 'react-player/lib/index' {
  declare module.exports: $Exports<'react-player/lib'>;
}
declare module 'react-player/lib/index.js' {
  declare module.exports: $Exports<'react-player/lib'>;
}
declare module 'react-player/lib/patterns.js' {
  declare module.exports: $Exports<'react-player/lib/patterns'>;
}
declare module 'react-player/lib/Player.js' {
  declare module.exports: $Exports<'react-player/lib/Player'>;
}
declare module 'react-player/lib/players/DailyMotion.js' {
  declare module.exports: $Exports<'react-player/lib/players/DailyMotion'>;
}
declare module 'react-player/lib/players/Facebook.js' {
  declare module.exports: $Exports<'react-player/lib/players/Facebook'>;
}
declare module 'react-player/lib/players/FilePlayer.js' {
  declare module.exports: $Exports<'react-player/lib/players/FilePlayer'>;
}
declare module 'react-player/lib/players/index' {
  declare module.exports: $Exports<'react-player/lib/players'>;
}
declare module 'react-player/lib/players/index.js' {
  declare module.exports: $Exports<'react-player/lib/players'>;
}
declare module 'react-player/lib/players/Mixcloud.js' {
  declare module.exports: $Exports<'react-player/lib/players/Mixcloud'>;
}
declare module 'react-player/lib/players/SoundCloud.js' {
  declare module.exports: $Exports<'react-player/lib/players/SoundCloud'>;
}
declare module 'react-player/lib/players/Streamable.js' {
  declare module.exports: $Exports<'react-player/lib/players/Streamable'>;
}
declare module 'react-player/lib/players/Twitch.js' {
  declare module.exports: $Exports<'react-player/lib/players/Twitch'>;
}
declare module 'react-player/lib/players/Vidyard.js' {
  declare module.exports: $Exports<'react-player/lib/players/Vidyard'>;
}
declare module 'react-player/lib/players/Vimeo.js' {
  declare module.exports: $Exports<'react-player/lib/players/Vimeo'>;
}
declare module 'react-player/lib/players/Wistia.js' {
  declare module.exports: $Exports<'react-player/lib/players/Wistia'>;
}
declare module 'react-player/lib/players/YouTube.js' {
  declare module.exports: $Exports<'react-player/lib/players/YouTube'>;
}
declare module 'react-player/lib/Preview.js' {
  declare module.exports: $Exports<'react-player/lib/Preview'>;
}
declare module 'react-player/lib/props.js' {
  declare module.exports: $Exports<'react-player/lib/props'>;
}
declare module 'react-player/lib/ReactPlayer.js' {
  declare module.exports: $Exports<'react-player/lib/ReactPlayer'>;
}
declare module 'react-player/lib/standalone.js' {
  declare module.exports: $Exports<'react-player/lib/standalone'>;
}
declare module 'react-player/lib/utils.js' {
  declare module.exports: $Exports<'react-player/lib/utils'>;
}
declare module 'react-player/mixcloud.js' {
  declare module.exports: $Exports<'react-player/mixcloud'>;
}
declare module 'react-player/scripts/post-publish.js' {
  declare module.exports: $Exports<'react-player/scripts/post-publish'>;
}
declare module 'react-player/scripts/pre-publish.js' {
  declare module.exports: $Exports<'react-player/scripts/pre-publish'>;
}
declare module 'react-player/soundcloud.js' {
  declare module.exports: $Exports<'react-player/soundcloud'>;
}
declare module 'react-player/streamable.js' {
  declare module.exports: $Exports<'react-player/streamable'>;
}
declare module 'react-player/twitch.js' {
  declare module.exports: $Exports<'react-player/twitch'>;
}
declare module 'react-player/vidyard.js' {
  declare module.exports: $Exports<'react-player/vidyard'>;
}
declare module 'react-player/vimeo.js' {
  declare module.exports: $Exports<'react-player/vimeo'>;
}
declare module 'react-player/wistia.js' {
  declare module.exports: $Exports<'react-player/wistia'>;
}
declare module 'react-player/youtube.js' {
  declare module.exports: $Exports<'react-player/youtube'>;
}
